config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  resources :department do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :update, :edit, :destroy]

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def show
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to department_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to department_path
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to root_path
  end

  private

    def department_params
      params.require(:department).permit(:department, :manager, :item)
    end

    def set_department
      @department = Department.find(params[:id])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :update, :edit, :destroy]

  def index
    @items = @Item.all
  end

  def new
    @item = Item.new
    render partial: "form"
  end

  def show
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to department_item_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to department_item_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

    def items_params
      params.require(:item).permit(:item, :descrition, :department)
    end

    def set_item
      @item = Item.find(params[:id])
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: @department, class: 'ui form') do |f| %>
  <%= f.label :department%>
  <%= f.text_field :department %>

  <%= f.submit nil, class: 'ui button primary' %>
<% end %>

app/views/departments/index.html.erb
<h1>DEPARTMENTS</h1>

<%= link_to 'Create a new department', new_department_path %>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<%= @department.department %>

<p>What would you like to do?</p>

  <%= link_to 'View Topics', sub_topics_path(@sub) %>
  
  
  <%= link_to 'Edit Sub', edit_sub_path(@sub) %>
  
  
  <%= link_to 'Delete Sub', @sub, method: :delete %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>